### PR TITLE
add Craftfile for Craftr 0.20.0-dev

### PR DESCRIPTION
**Pull request by NiklasRosenstein**
Builds successful on Ubuntu 15.10.

```
niklas@sunbird:~/Desktop/baremetal-hi$ craftr -ebcc -N -v
Cleaning... 5 files.
[1/5] craftr-rts rules.render_template /home/niklas/Desktop/baremetal-hi/Craftr.link-template.ld /home/niklas/Desktop/baremetal-hi/build/baremetal_hi/link.ld STARTUP_OBJ=baremetal_hi/obj/startup.o
[2/5] arm-eabi-gcc -c /home/niklas/Desktop/baremetal-hi/startup.S -o /home/niklas/Desktop/baremetal-hi/build/baremetal_hi/obj/startup.o -DRESET_ON_MAIN_COMPLETE -DBmArm -Wall -O0 -MD -MP -MF /home/niklas/Desktop/baremetal-hi/build/baremetal_hi/obj/startup.o.d -mcpu=arm926ej-s -nodefaultlibs -nostdlib -nostartfiles -ffreestanding
[3/5] arm-eabi-gcc -x c -c /home/niklas/Desktop/baremetal-hi/test.c -o /home/niklas/Desktop/baremetal-hi/build/baremetal_hi/obj/test.o -DBmArm -Wall -O0 -MD -MP -MF /home/niklas/Desktop/baremetal-hi/build/baremetal_hi/obj/test.o.d -mcpu=arm926ej-s -nodefaultlibs -nostdlib -nostartfiles -ffreestanding
[4/5] arm-eabi-gcc /home/niklas/Desktop/baremetal-hi/build/baremetal_hi/obj/test.o -Wl,-T,baremetal_hi/link.ld -mcpu=arm926ej-s -nodefaultlibs -nostdlib -nostartfiles -ffreestanding -o /home/niklas/Desktop/baremetal-hi/build/test.elf
[5/5] arm-eabi-objcopy -O binary /home/niklas/Desktop/baremetal-hi/build/test.elf /home/niklas/Desktop/baremetal-hi/build/baremetal_hi/obj/testbin
```

### CODE REVIEW

**Comment by winksaville** [comment]
Ill review/test later today or tomorrow, txs.

**Comment by NiklasRosenstein** [comment]
I wonder why my replies to your comments in the commits don't pop up here in the Pull Request.

**Comment by NiklasRosenstein** [comment]
Please make sure you have the newest version of Craftr when testing the changes.

**Comment by winksaville** [comment]
I will, the inline commenting isn't as good as Gerrit which is what I'm
used to:(

**Comment by winksaville** [comment]
I tried the following using -p but I must be doing something wrong. Also there is a typo "unusued" should be "unused".

```
$ mkdir build-craftr
$ cd build-craftr/
$ craftr -e -p ..
craftr: [INFO ] (baremetal_hi|L36): unusued options for compile(): {'outputs'}
$ ninja -t targets
baremetal_hi.run: baremetal_hi.run
baremetal_hi.t_linker_script: phony
baremetal_hi.t_startup: phony
baremetal_hi.t_test: phony
baremetal_hi.t_testbin: phony
baremetal_hi.t_testelf: phony
$ ninja 
ninja: error: '/home/wink/prgs/baremetal-hi/build-craftr/baremetal_hi/link.ld', needed by '/home/wink/prgs/baremetal-hi/build-craftr/test.elf', missing and no known rule to make it
```

**Comment by NiklasRosenstein** [comment]
Did you also pull the latest version from my baremetal-hi branch? There should be no `craftr: [INFO ] (baremetal_hi|L36): unusued options for compile(): {'outputs'}` warning in the latest version.

> Also there is a typo "unusued" should be "unused".

Thanks, I've updated the string.

**Comment by winksaville** [comment]
I've now done but still didn't work, could you give me the command sequence
you use.

**Pull request merged**
